module.exports = {
    match: (msg) => msg.startsWith('/help'),
    execute: async (ctx, deps) => {
        let reply = '--- PANDUAN PERINTAH STELLA ---\n\n';
        reply += '🔹 /stats - Cek statistik, level, XP, dan model AI.\n';
        reply += '🔹 /skills - Lihat daftar skill tree yang dikuasai.\n';
        reply += '🔹 /learn - Lihat topik favorit, jam aktif, dan pembelajaran Stella.\n';
        reply += '🔹 /patches - Lihat patch otomatis dari Self-Modifier.\n';
        reply += '🔹 /rules - Lihat aturan kustom yang aktif.\n';
        reply += '🔹 /reflect - Jalankan self-reflection manual.\n';
        reply += '🔹 /settings - Buka menu pengaturan interaktif (8 kategori).\n';
        reply += '🔹 /model [codex|gemini|groq] - Ganti model AI Stella.\n';
        reply += '🔹 /clear - Reset riwayat chat (jika Stella error).\n';
        reply += '🔹 /ping - Cek apakah Stella aktif.\n';
        reply += '🔹 /restart - Restart total sistem Stella.\n';
        reply += '🔹 /reload - Reload semua command tanpa restart.\n';
        reply += '🔹 /leave - Keluar dari grup.\n';
        reply += '🔹 /kick @user - Tendang anggota dari grup (butuh admin).\n';
        reply += '\n--- DISCORD VOICE ---\n';
        reply += '🔊 /join - Stella masuk voice channel (kamu harus di VC dulu).\n';
        reply += '🔇 /leave atau /keluar - Stella keluar dari voice channel.\n';
        reply += '\n--- KEMAMPUAN MULTIMEDIA & TOOLS ---\n';
        reply += '🎨 generate_image - Bikin gambar dari teks (Pollinations AI).\n';
        reply += '🎤 generate_voice - Ubah teks jadi voice note (gTTS).\n';
        reply += '📤 send_media - Kirim foto/video/audio/dokumen ke chat.\n';
        reply += '📥 download_file - Unduh file dari URL internet.\n';
        reply += '📸 screenshot_web - Screenshot halaman web.\n';
        reply += '🔍 search_web - Cari informasi di web (DuckDuckGo).\n';
        reply += '🌐 fetch_webpage - Baca konten halaman web.\n';
        reply += '📂 read_file / write_file - Baca/tulis file di server.\n';
        reply += '⚡ execute_command - Jalankan perintah terminal.\n';
        reply += '🕐 get_time - Cek waktu & tanggal real-time.\n';
        reply += '🖥 check_system - Cek status sistem.\n';
        reply += '📋 settings_ui - Menu pengaturan interaktif.\n';
        reply += '🤖 telegram_manager - Manajemen bot Telegram.\n';
        reply += '\n--- PLATFORM & PROVIDER ---\n';
        reply += '📱 Telegram: chat biasa atau /command\n';
        reply += '💬 Discord: @Stella untuk chat, /join dan /leave untuk voice\n';
        reply += '🧠 AI Provider: DeepSeek (utama), Gemini (fallback media), Groq/Llama 3.3, Codex\n';
        reply += '🔄 Agentic Loop + Behavior Tree routing\n';
        reply += '🧬 Deep Brain (TensorFlow.js) + Evolution XP/Level\n';
        reply += '📝 Memory per-user + Auto-Research + Self-Modifier\n';
        reply += '\n💡 Chat aja langsung! Aku bisa ngobrol, riset, bikin gambar, voice, dan bantu coding.';
        ctx.directReply = reply;
        ctx.skipAI = true;
        return deps.STATUS.SUCCESS;
    }
};